controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 50

    dingo_joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      # publish_rate: 50

    dingo_velocity_controller:
      type: diff_drive_controller/DiffDriveController

dingo_velocity_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel"]
    right_wheel_names: ["right_wheel"]
    publish_rate: 50
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

    cmd_vel_timeout: 0.25
    use_stamped_vel: false

    # Odometry fused with IMU is published by robot_localization, so
    # no need to publish a TF based on encoders alone.
    # CURRENTLY: no tf is published, so for now let's just take tf from just encoders
    enable_odom_tf: true

    # Wheel separation and radius
    wheel_separation: 0.44
    wheel_radius: 0.049

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    # TODO: measure on actual vehicle: how?
    linear.x.has_velocity_limits      : true
    linear.x.max_velocity             : 1.3   # m/s
    linear.x.has_acceleration_limits  : true
    linear.x.max_acceleration         : 1.0   # m/s^2
    linear.x.has_jerk_limits          : false
    # TODO: measure on actual vehicle: how?
    angular.z.has_velocity_limits     : true
    angular.z.max_velocity            : 4.0   # rad/s
    angular.z.has_acceleration_limits : true
    angular.z.max_acceleration        : 2.0   # rad/s^2
    angular.z.has_jerk_limits         : false
