# Teleop configuration for PS4 Navigation joystick
teleop_twist_joy:
  axis_linear:
    x: 1
    y: 0
  scale_linear:
    x: 0.4
    y: 0.4
  scale_linear_turbo:
    x: 2.0 # TODO: should this be 1.0?
    y: 2.0 # TODO: should this be 1.0?
  axis_angular:
    yaw: 3
  scale_angular:
    yaw: 1.4 # TODO: should this be 1.0?
  scale_angular_turbo:
    yaw: 1.4 # TODO: should this be 1.0?
  enable_button: 4
  enable_turbo_button: 5
joy_node:
  deadzone: 0.1 # TODO: should this be 0.02?
  autorepeat_rate: 20
  dev: /dev/input/ps4
